version: "3"
services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "80:8080"
      - "5000:5000"
    volumes:
      - jenkins_home:/var/jenkins_home
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    
#docker run -p 8080:8080 -p 50000:50000 -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts