version: '2'
services:
  jenkins:
    image: 'jenkins:latest'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins:/var/jenkins_home'
volumes:
  jenkins:
    driver: local
